# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('ingredients', models.ManyToManyField(to='rest.Ingredient')),
            ],
        ),
    ]
