# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20170506_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='condiments',
            field=models.ManyToManyField(to='rest.Condiment'),
        ),
    ]
